version: '3.8'
services:
  app:
    container_name: sota_back
    restart: always
    build: .
    ports:
      - '0.0.0.0:3000:3000'
    volumes:
      - 'sota-storage:/storage'
  mongo:
    container_name: mongo_sota
    restart: always
    image: 'mongo:4.1.8-xenial'
    volumes:
      - './mongodb.conf:/data/configdb/mongodb.conf'
      - 'mongoData:/data/db'
volumes:
  sota-storage:
    external: true
  mongoData:
    external: true