name: CI
on:
    # События, которые запускают jobs
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

# jobs запускаются параллельно, если не указана последовательность
jobs:
  deploy:
    runs-on: self-hosted
    environment: prod
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "PORT=${{ secrets.DEPLOY_PORT }}" > .env
          echo "APP_PORT=${{ secrets.APP_PORT }}" >> .env
          echo "DB_URL=${{ secrets.DB_URL }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env

      - name: Display .env file
        run: |
          cat .env
      - name: Deploy on the Same Server
        run: |
         ls&&docker-compose pull && docker-compose up -d --build