name: CI
on:
    # События, которые запускают jobs
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

# jobs запускаются параллельно, если не указана последовательность
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: 'Create env file'
        env:
          PORT: ${{ secrets.DEPLOY_PORT }}
          APP_PORT: ${{ secrets.APP_PORT }}
          DB_URL: ${{ secrets.DB_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          touch .env
          echo "PORT=${PORT}" >> .env
          echo "APP_PORT=${APP_PORT}" >> .env
          echo "DB_URL=${DB_URL}" >> .env
          echo "JWT_SECRET=${JWT_SECRET}" >> .env
      - name: Deploy on the Same Server
        run: |
         ls&&docker-compose pull && docker-compose up -d --build